# Underworld 2 

---

![Image showing map of results](./Figures/MohoSurfaceGradient-ClusteredGrids.png)

_Nice image_

--- 

[_Underworld 2_](http://www.underworldcode.org) is a python-friendly version of the Underworld code which provides a programmable and flexible front end to all the functionality of the code running in a parallel HPC environment. This gives signficant advantages to the user, with access to the power of python libraries for setup of complex problems, analysis at runtime, problem steering, and multi physics coupling. While Underworld2 embraces Jupyter Notebooks as the preferred modelling environment, only standard python is required.

The Underworld2 development team is based in Melbourne, Australia at the University of Melbourne and at Monash University led by Louis Moresi. We would like to acknowledge AuScope Simulation, Analysis and Modelling for providing long term funding which has made the project possible. Additional funding for specific improvements and additional functionality has come from the Australian Research Council (http://www.arc.gov.au). The python toolkit was funded by the NeCTAR eresearch_tools program. Underworld was originally developed in collaboration with the Victorian Partnership for Advanced Computing.

#### Build status

Lastest stable release (master branch) [![Build Status](http://130.56.252.251:32779/buildStatus/icon?job=master)](http://130.56.252.251:32779/job/master/)

Development branch - [![Build Status](http://130.56.252.251:32779/buildStatus/icon?job=uw-dev)](http://130.56.252.251:32779/job/uw-dev/)


## Site Map

The jupyter notebooks provided as examples are given below

### User guide

  - [01_GettingStarted.ipynb](user_guide/01_GettingStarted.ipynb)
  - [02_TheMesh.ipynb](user_guide/02_TheMesh.ipynb)
  - [03_MeshVariable.ipynb](user_guide/03_MeshVariable.ipynb)
  - [04_Swarms.ipynb](user_guide/04_Swarms.ipynb)  
  - [05_Functions.ipynb](user_guide/05_Functions.ipynb)  
  - [06_Systems.ipynb](user_guide/06_Systems.ipynb)  
  - [07_Utilities.ipynb](user_guide/07_Utilities.ipynb)  
  - [08_Visualisation.ipynb](user_guide/08_Visualisation.ipynb)
  - [09_StokesSolver.ipynb](user_guide/09_StokesSolver.ipynb)

### Tutorials

  - [Convection Tutorial](tutorials/ConvectionTutorial/Notebooks/010-Overview.ipynb)
  - [Viscoelasticity Tutorial](tutorials/ViscoelasticTutorial/010-Overview.ipynb)
  - [Basin Framework](tutorials/BasinFrameworkTutorial)


### Reproducing published results




### Underworld Docker Usage
------------

Most new users may wish to use the Kitematic GUI to download and run Underworld. Simply search for 'underworldcode/underworld2' within Kitematic, and then click 'CREATE' to launch a container. You will eventually wish to modify your container settings (again through Kitematic) to enable local folder volume mapping, which will allow you to access your local drives within your container. 

For Linux users, and those who prefer the command line, the following minimal command should be sufficient to access the Underworld2 Jupyter Notebook examples: 

```bash
   docker run --rm -p 8888:8888 underworldcode/underworld2
```


In [9]:
ls publications/DaviesRawlinson-2014/

daviesRawlinson-2014-figDR6.ipynb


Installation
-----------

The package can be installed standalone using `pip` 
or it can be run through docker without needing specific installation. 

These notebooks can be viewed with jupyter but will only run if all the software dependencies have
been installed (see [Installation through `pip`](#Installation-through-pip) below. 

In nearly every instance we recommend using the (self-contained) docker version. 
We have provided some useful `bash` shortcuts that make the docker commands
easier to remember (see [Installation through docker](#Installation-through-docker) below).



### Installation through docker


First it is necessary to install the free __docker, community edition__ from the  [docker store](https://store.docker.com/search?offering=community&type=edition) for your platform.

```bash
# Download the image with the scripts and data
docker pull lmoresi/docker-miller-moho:1.1
```

That's it ! 

To test the installation, try the following

####  Command line docker examples

This help message

```bash
# print help message (i.e. usage)
docker run --rm lmoresi/docker-miller-moho:1.1 help
```

Install the bash helpers in the current directory
```bash
# print help message (i.e. usage)
docker run --rm lmoresi/docker-miller-moho:1.1 bash_utils > msmoho_bash_utils.sh
source msmoho_bash_utils.sh
```

Install the documentation / scripts and notebooks in the current directory
```bash
# print help message (i.e. usage)
source msmoho_bash_utils.sh
msmoho-docker-sh install_examples
```

Run a local python script  

```bash
# run  my_script.py with python in the docker container
source msmoho_bash_utils.sh
msmoho-docker-sh my_script.py

```

### Installation through pip (or conda)

The installation of the python package is straightforward but
there is a dependency on numpy and on stripy which may require
an installed fortran compiler. If this proves problematic, the
docker version may simply be the best choice.

```bash
   #! /bin/env bash 9
   # install the main package
   # stripy and numpy are installed as dependencies by pip
   # but we can do this explicitly to manage versions and
   # check for errors
   
   pip install numpy
   pip install stripy
   
   # stripy and numpy
   # as they embed fortran and C packages
   # miller_alaskamoho_srl2018 itself is pure python
   
   pip install miller_alaskamoho_srl2018
```

The following script tests the installation:

```python
    #! /bin/env python 
    import numpy as np 
    try:
        import miller_alaskamoho_srl2018 as alaskamoho
    except ImportError:
        print ("Problem importing the alaska moho package")
    
    # Check the data files exist / can be read
    # [('lon', '<f8'), ('lat', '<f8'), ('moh', '<f8') ... etc
    # [-174.197495 -171.703506 -170.247696 -168.854996 -168.161896]
    # [43.61043017 34.75098075 37.34819411]
    
    mohoraw = alaskamoho.MohoErr
    print(mohoraw.dtype)
    print(mohoraw['lon'][0:5])
    print(mohoraw['moh'][0:5])
    
    # Check to see if the interpolator works
    # [43.61043017 34.75098075 37.34819411]
    
    moho_model = alaskamoho.MohoModel_opt
    lons = np.array([-150, -155, -160])
    lats = np.array([60, 65, 70])
    print(moho_model.value_at_lonlat_degrees(lons, lats, order=1))
   
    # install documentation in user-specified location
    # Should install in the current directory as AlaskaMohoExamples
    
    alaskamoho.documentation.install_documentation(path=None)
```

If you install the documentation in the form of jupyter notebooks, then to view them,
you also need to install some dependencies. Specifically:


```bash

   # The jupyter notebook system (and dependencies)
   pip install jupyter
   
   # scipy is used in some examples
   pip install scipy
   
   # cartopy is used to plot examples
   # (may be necessary to install the shapely package first)
   
   pip install --no-binary :all: shapely
   pip install cartopy 
   
   # We need litho1pt0 to re-build the model files
   
   pip install litho1pt0
   
   # We use lavavu for the interactive visualisation of the surfaces
   
   pip install lavavu
   
   # pip install gdal is optional: it is used for shaded relief images of the 
   # maps and also requires a download of the relevant image file.
   
   pip install gdal 
```
   
   
If you only wish to browse the documentation / examples or see how we built the model, why not use the docker version !